/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.ijse.coursework.view;

import edu.ijse.coursework.controller.BookCategoryController;
import edu.ijse.coursework.controller.BookController;
import edu.ijse.coursework.dto.BookCategoryDto;
import edu.ijse.coursework.dto.BookDto;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sithum
 */
public class BookCategoryView extends javax.swing.JFrame {
    private final BookCategoryController BOOK_CATEGORY_CONTROLLER;
    private final BookController BOOK_CONTROLLER;

    /**
     * Creates new form BookCategoryView
     */
    public BookCategoryView() throws Exception {
        BOOK_CATEGORY_CONTROLLER=new BookCategoryController();
        BOOK_CONTROLLER=new BookController();
        initComponents();
        loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bookCategoryLabel = new javax.swing.JLabel();
        bookCategoryField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        categoryIdLabel = new javax.swing.JLabel();
        categoryIdField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        bookCategoryTabel = new javax.swing.JTable();
        saveButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        bookDataLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bookCategoryLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bookCategoryLabel.setText("Book Category");

        bookCategoryField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        searchButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        categoryIdLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        categoryIdLabel.setText("Category ID");

        categoryIdField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        bookCategoryTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        bookCategoryTabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookCategoryTabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(bookCategoryTabel);

        saveButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        updateButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        deleteButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(categoryIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(categoryIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(bookCategoryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(bookCategoryField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(deleteButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saveButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(updateButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(searchButton)
                        .addGap(30, 30, 30)
                        .addComponent(bookDataLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchButton)
                    .addComponent(categoryIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(categoryIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookDataLabel))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bookCategoryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bookCategoryField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addComponent(saveButton)
                        .addGap(26, 26, 26)
                        .addComponent(updateButton)
                        .addGap(28, 28, 28)
                        .addComponent(deleteButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
//        try {
//            // TODO add your handling code here:
//            searchBook();
//        } catch (Exception ex) {
//            Logger.getLogger(BookCategoryView.class.getName()).log(Level.SEVERE, null, ex);
//        }
        
    }//GEN-LAST:event_searchButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        try {
            // TODO add your handling code here:
            saveCategory();
        } catch (Exception ex) {
            Logger.getLogger(BookCategoryView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        try {
            // TODO add your handling code here:
            updateCategory();
        } catch (Exception ex) {
            Logger.getLogger(BookCategoryView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        try {
            deleteCategory();
        } catch (Exception ex) {
            Logger.getLogger(BookCategoryView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void bookCategoryTabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookCategoryTabelMouseClicked
        try {
            // TODO add your handling code here:
            setCategory();
        } catch (Exception ex) {
            Logger.getLogger(BookCategoryView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bookCategoryTabelMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(BookCategoryView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(BookCategoryView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(BookCategoryView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(BookCategoryView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new BookCategoryView().setVisible(true);
//            }
//        });
//    }
    
    public void loadTable()throws Exception{
        try {
            String columns[]={"Category Id","Book Category"};
            DefaultTableModel dtm=new DefaultTableModel(columns,0){
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
                
            };
            bookCategoryTabel.setModel(dtm);
            ArrayList<BookCategoryDto> bookCategoryDtos=BOOK_CATEGORY_CONTROLLER.getAll();
            for (BookCategoryDto bookCategoryDto:bookCategoryDtos){
                Object[] rowData={bookCategoryDto.getCategoryId(),bookCategoryDto.getBookCategory()};
                dtm.addRow(rowData);
            }
            
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
    }
    
    public void saveCategory()throws Exception{
        try {
            BookCategoryDto dto=new BookCategoryDto(categoryIdField.getText(),bookCategoryField.getText());
            String rsp=BOOK_CATEGORY_CONTROLLER.save(dto);
            JOptionPane.showMessageDialog(this, rsp);
            clearForm();
            loadTable();
            
            
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, e.getMessage());
            
        }
        
        
    }
    
      public void clearForm() {
        categoryIdField.setText("");
        bookCategoryField.setText("");
        bookDataLabel.setText("");
        
    }
    public void updateCategory()throws Exception{
        try {
            BookCategoryDto dto=new BookCategoryDto(categoryIdField.getText(),bookCategoryField.getText());
            String rsp=BOOK_CATEGORY_CONTROLLER.update(dto);
            JOptionPane.showMessageDialog(this, rsp);
            clearForm();
            loadTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    public void setCategory()throws Exception{
        try {
            String Code= (String)bookCategoryTabel.getValueAt(bookCategoryTabel.getSelectedRow(), 0);
            BookCategoryDto dto=BOOK_CATEGORY_CONTROLLER.get(Code);
            if (dto!=null){
                categoryIdField.setText(dto.getCategoryId());
                bookCategoryField.setText(dto.getBookCategory());
            }else{
                JOptionPane.showMessageDialog(this, "Category not Found");
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
    }
    
    public void deleteCategory()throws Exception{
        try {
            String id=categoryIdField.getText();
            String rsp=BOOK_CATEGORY_CONTROLLER.delete(id);
            JOptionPane.showMessageDialog(this, rsp);
            clearForm();
            loadTable();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
    }
   
//    public void searchBook()throws Exception{
//        try {
//            String id=bookIdField.getText();
//            BookDto dto=BOOK_CONTROLLER.get(id);
//            if (dto!=null){
//                bookDataField.setText(dto.getBookName()+" | "+dto.getAuthor());
//            }else{
//                bookDataField.setText("Book Not Found");
//            }
//        } catch (Exception e) {
//            e.printStackTrace();
//            JOptionPane.showMessageDialog(this, e.getMessage());
//        }
//        
//    }
      

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bookCategoryField;
    private javax.swing.JLabel bookCategoryLabel;
    private javax.swing.JTable bookCategoryTabel;
    private javax.swing.JLabel bookDataLabel;
    private javax.swing.JTextField categoryIdField;
    private javax.swing.JLabel categoryIdLabel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
