/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.ijse.coursework.view;

import edu.ijse.coursework.controller.BookController;
import edu.ijse.coursework.controller.BorrowController;
import edu.ijse.coursework.controller.MemberController;
import edu.ijse.coursework.dto.BookDto;
import edu.ijse.coursework.dto.BorrowDto;
import edu.ijse.coursework.dto.MemberDto;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author Sithum
 */
public class BorrowView extends javax.swing.JFrame {
    private final BorrowController BORROW_CONTROLLER;
    private final MemberController MEMBER_CONTROLLER;
    private final BookController BOOK_CONTROLLER;
    private final ArrayList<BorrowDto> borrowDtos=new ArrayList<>();
    
    /**
     * Creates new form BorrowView
     */
    public BorrowView()throws Exception{
        this.BORROW_CONTROLLER=new BorrowController();
        this.MEMBER_CONTROLLER=new MemberController();
        this.BOOK_CONTROLLER=new BookController();
        
        initComponents();
        loadTable();
        setTitle("Borrow Management");
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        memberIdLabel = new javax.swing.JLabel();
        memberIdField = new javax.swing.JTextField();
        memberSearchButton = new javax.swing.JButton();
        memberDataLabel = new javax.swing.JLabel();
        bookIdLabel = new javax.swing.JLabel();
        bookIdField = new javax.swing.JTextField();
        bookSearchButton = new javax.swing.JButton();
        bookDataLabel = new javax.swing.JLabel();
        issueDateLabel = new javax.swing.JLabel();
        issuDatePicker = new com.toedter.calendar.JDateChooser();
        returnDateLabel = new javax.swing.JLabel();
        returnDatePicker = new com.toedter.calendar.JDateChooser();
        addToTable = new javax.swing.JButton();
        placeBorrow = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        borrowTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        memberIdLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        memberIdLabel.setForeground(new java.awt.Color(51, 51, 51));
        memberIdLabel.setText("Member ID");

        memberIdField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        memberSearchButton.setBackground(new java.awt.Color(74, 144, 226));
        memberSearchButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        memberSearchButton.setForeground(new java.awt.Color(255, 255, 255));
        memberSearchButton.setText("Search");
        memberSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memberSearchButtonActionPerformed(evt);
            }
        });

        memberDataLabel.setForeground(new java.awt.Color(255, 255, 255));

        bookIdLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bookIdLabel.setForeground(new java.awt.Color(51, 51, 51));
        bookIdLabel.setText("Book ID");

        bookIdField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        bookSearchButton.setBackground(new java.awt.Color(74, 144, 226));
        bookSearchButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bookSearchButton.setForeground(new java.awt.Color(255, 255, 255));
        bookSearchButton.setText("Search");
        bookSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookSearchButtonActionPerformed(evt);
            }
        });

        bookDataLabel.setBackground(new java.awt.Color(204, 204, 204));
        bookDataLabel.setForeground(new java.awt.Color(255, 255, 255));

        issueDateLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        issueDateLabel.setForeground(new java.awt.Color(51, 51, 51));
        issueDateLabel.setText("Issue Date");

        returnDateLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        returnDateLabel.setForeground(new java.awt.Color(51, 51, 51));
        returnDateLabel.setText("Return Date");

        addToTable.setBackground(new java.awt.Color(74, 144, 226));
        addToTable.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addToTable.setForeground(new java.awt.Color(255, 255, 255));
        addToTable.setText("Add To Table");
        addToTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToTableActionPerformed(evt);
            }
        });

        placeBorrow.setBackground(new java.awt.Color(74, 144, 226));
        placeBorrow.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        placeBorrow.setForeground(new java.awt.Color(255, 255, 255));
        placeBorrow.setText("Place Borrow");
        placeBorrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeBorrowActionPerformed(evt);
            }
        });

        borrowTable.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        borrowTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        borrowTable.setSelectionBackground(new java.awt.Color(80, 227, 194));
        jScrollPane1.setViewportView(borrowTable);

        jPanel2.setBackground(new java.awt.Color(74, 144, 226));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Borrow Books");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 866, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(memberIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bookIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(issueDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(returnDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGap(48, 48, 48)
                                    .addComponent(addToTable)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                                    .addComponent(placeBorrow, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(returnDatePicker, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(issuDatePicker, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(memberIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bookIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addComponent(memberSearchButton)
                                        .addGap(33, 33, 33)
                                        .addComponent(memberDataLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                                        .addComponent(bookSearchButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(bookDataLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(140, 140, 140)))))))
                .addContainerGap(7, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(352, 352, 352)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(memberDataLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(memberIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(memberSearchButton))
                    .addComponent(memberIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bookIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bookIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(issueDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bookSearchButton)
                            .addComponent(bookDataLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(issuDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(returnDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(returnDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addToTable)
                    .addComponent(placeBorrow))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void memberSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memberSearchButtonActionPerformed
        try {
            // TODO add your handling code here:
            searchMember();
        } catch (Exception ex) {
            Logger.getLogger(BorrowView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_memberSearchButtonActionPerformed

    private void bookSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookSearchButtonActionPerformed
        try {
            // TODO add your handling code here:
            searchBook();
        } catch (Exception ex) {
            Logger.getLogger(BorrowView.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_bookSearchButtonActionPerformed

    private void addToTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToTableActionPerformed
        try {
            // TODO add your handling code here:
            addToTable();
        } catch (Exception ex) {
            Logger.getLogger(BorrowView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addToTableActionPerformed

    private void placeBorrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeBorrowActionPerformed
        try {
            // TODO add your handling code here:
            placeBorrow();
            
        } catch (Exception ex) {
            Logger.getLogger(BorrowView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_placeBorrowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BorrowView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BorrowView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BorrowView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BorrowView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new BorrowView().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(BorrowView.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
    public void searchMember()throws Exception{
        try {
            String id=memberIdField.getText();
            MemberDto dto=MEMBER_CONTROLLER.get(id);
            if (dto!=null){
                memberDataLabel.setText(dto.getName()+"-"+dto.getContactInfo()+"-"+dto.getAddress());
            }else{
                memberDataLabel.setText("Member Not Found!");
            }
            
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
    }
    
    public void searchBook()throws Exception{
        try {
            String id=bookIdField.getText();
            BookDto dto=BOOK_CONTROLLER.get(id);
            if (dto!=null){
                bookDataLabel.setText(dto.getBookName()+"-"+dto.getAuthor()+"- COUNT-"+dto.getCount());
            }else{
                bookDataLabel.setText("Book Not Found");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
    }
    
    public void loadTable()throws Exception{
        String columns[]={"Member ID","Book ID","Issue Date","Return Date"};
        DefaultTableModel dtm=new DefaultTableModel(columns,0){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
            }
            
        };
        
        borrowTable.setModel(dtm);     
        JTableHeader header=borrowTable.getTableHeader();
        header.setBackground(new Color(74,144,226));
        header.setForeground(Color.white);
        header.setFont(new Font("Segoe UI",Font.BOLD,14));
    }
    
    public void addToTable()throws Exception{
        BorrowDto dto=new BorrowDto();
        dto.setMemberId(memberIdField.getText());
        dto.setBookId(bookIdField.getText());
        dto.setIssueDate(issuDatePicker.getDate());
        dto.setReturnDate(returnDatePicker.getDate());
        
        borrowDtos.add(dto);
        Object rowData[]={dto.getMemberId(),dto.getBookId(),dto.getIssueDate(),dto.getReturnDate()};
        DefaultTableModel dtm=(DefaultTableModel)borrowTable.getModel();
        dtm.addRow(rowData);
        
        
    }
    
    public void placeBorrow()throws Exception{
        try {
            BorrowDto borrowDto=new BorrowDto();
            borrowDto.setMemberId(memberIdField.getText());
            borrowDto.setBookId(bookIdField.getText());
            borrowDto.setIssueDate(issuDatePicker.getDate());
            borrowDto.setReturnDate(returnDatePicker.getDate());
            
            String rsp=BORROW_CONTROLLER.placeBorrow(borrowDto);
            JOptionPane.showMessageDialog(this, rsp);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addToTable;
    private javax.swing.JLabel bookDataLabel;
    private javax.swing.JTextField bookIdField;
    private javax.swing.JLabel bookIdLabel;
    private javax.swing.JButton bookSearchButton;
    private javax.swing.JTable borrowTable;
    private com.toedter.calendar.JDateChooser issuDatePicker;
    private javax.swing.JLabel issueDateLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel memberDataLabel;
    private javax.swing.JTextField memberIdField;
    private javax.swing.JLabel memberIdLabel;
    private javax.swing.JButton memberSearchButton;
    private javax.swing.JButton placeBorrow;
    private javax.swing.JLabel returnDateLabel;
    private com.toedter.calendar.JDateChooser returnDatePicker;
    // End of variables declaration//GEN-END:variables
}
